### ISSUE TITLE
Error Authent

### ISSUE THREAD

**Issue by yannickIT** [delphiki/MMM-Pronote#27]
Bonjour,

J'ai viens d'installer le module est je rencontre une difficulté pour authentification.
J'ai activé le mode Débug dans le fichier de conf. Vous trouverez ci-dessous l'erreur.
Pour information authentification fonctionne très bien via application "Pronote" de mon téléphone.
Mais je n'utilise pas le même portail web via le PC mais celui là => https://connexion.enthdf.fr/ " je suis obligé de le renseigner "OIse" et non la région en suite je suis redirigé par la suite vers https://teleservices.ac-amiens.fr/login/ avec mon compte et authentification fonctionne .  
![image](https://user-images.githubusercontent.com/28387595/99186058-f1f0fe80-274d-11eb-95c7-a1026128b455.png)

![image](https://user-images.githubusercontent.com/28387595/99185971-6aa38b00-274d-11eb-98d0-7af258b994bd.png)

A mon avis le probleme est sur le département car je suis obligé de le renseigner "OIse" 
J'ai bien configuré le fichier avec le paramètre =>  cas: "hdf", idem pour url => 

sur le miroir il y a  afficher " Error.... aucune donnée"  
 
![image](https://user-images.githubusercontent.com/28387595/99185723-f9afa380-274b-11eb-938e-dbdfc4663971.png)

Pouvez vous m'aider merci.

**Comment by bugsounet** [comment]
bonjour,

Les identifiants sont tout simplement incorrect ;)
Je pense que vous utilisez les identifiants de 'teleservices' pour vous connecter alors que pronote demande les identifants de 'ENT' (Je sais, ils sont compliqué l'éducation nationale)

1) Deja bonne nouvelle on est plus ou moins de la meme région (CAS: hdf)
2) essayez de vous connecter sur le site de l'ENT directement [https://enthdf.fr/auth/login](https://enthdf.fr/auth/login)

vous pouvez ainsi récupérer tout ce qu'il faudra pour vous connecté :)

l'education nationnale a fait un systeme de login ainsi pour hdf : auth teleservices -> auth ent -> auth pronote
Pronote demande ceci : auth ENT -> auth pronote

Pour le moment je n'arrive pas a joindre les 3 sur hdf

donc il faut recuperer vos identifiant ENT ;)
Ils sont différent de teleservices, voila pourquoi il vous indique "wrong user credentials" (identifiant incorrect)

**Comment by yannickIT** [comment]
OK  c good Merci pour ton aide et ta réactivité.  j'ai donc reset mon password du portail  ENT et non le "teleservice" 

J'ai bien les infos 👍 👍 👍
